name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker images
      run: |
        docker build -t gcr.io/$PROJECT_ID/app:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/app:${{ github.sha }}

    - name: Deploy to Google Kubernetes Engine
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
        kubectl set image deployment/app app=gcr.io/$PROJECT_ID/app:${{ github.sha }}
        kubectl rollout status deployment/app

    - name: Update database schema
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Add commands to update the database schema
        # This might involve running migrations or applying SQL scripts
        # Example:
        # kubectl exec -it $(kubectl get pod -l app=db -o jsonpath="{.items[0].metadata.name}") -- /bin/sh -c "psql -U $DB_USER -d $DB_NAME -f /path/to/migration/script.sql"

    - name: Run post-deployment tests
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Add commands to run post-deployment tests
        # This might involve running integration tests or smoke tests
        # Example:
        # kubectl exec -it $(kubectl get pod -l app=test-runner -o jsonpath="{.items[0].metadata.name}") -- /bin/sh -c "npm run integration-tests"

    - name: Notify deployment status
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment to GKE ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}